// <auto-generated />
using KarekodBarkodUygulaması.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KarekodBarkodUygulaması.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220818085906_InıtialCreate")]
    partial class InıtialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("KarekodBarkodUygulaması.Models.Product", b =>
                {
                    b.Property<int>("productID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("karekodImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("productAciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("productAdet")
                        .HasColumnType("int");

                    b.Property<string>("productBarkod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("productBarkodImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("productFiyat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("productImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("productName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("productID");

                    b.ToTable("products");
                });
#pragma warning restore 612, 618
        }
    }
}
